Connect google drive to the colab

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


Download Dataset from Kaggle

In [ ]:
import os
os.chdir('/content/gdrive/MyDrive')
!wget -c 'https://storage.googleapis.com/kaggle-data-sets/1646010/2702383/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20220529%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20220529T044818Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=8408ae94665ef094c937b32195f30c98ddf923804caee41504b4e4c608fa18ad54548ffb0b72bb3623fccef1f4fc65e4a1a71efc37da825f4ca067e50e2b28b33260dbeac175bb28bfd44623599dec8777cd7847c6f81210322dcb95929c91cbf747489fe91adf085100efbc3d887e0708cdd055ee706d59364b12ad1025a73229c3d721bb2295bd311bf51016847c975baeb95c72c66b61db0152d28b0075ea4416f1112622210984877f27ba8b706e7dc3748a104c6fd91d215cb11ce0759a87e62e6029da79b97bcf721aecb1899c18caa521226d108dadde276c8a868bef5e9c2ea58371b293a588fa732e63c54b9d7514e03d7cffe089f2fde102dfd555' --no-check-certificate

Extract dataset ZIP file

In [ ]:
import zipfile

zip_ref = zipfile.ZipFile("/content/gdrive/MyDrive/data.zip", "r")
zip_ref.extractall()
zip_ref.close()

Import Libraries

In [ ]:
import cv2     # for capturing videos
import math   # for mathematical operations
import matplotlib.pyplot as plt    # for plotting the images
%matplotlib inline
import pandas as pd
from keras.preprocessing import image   # for preprocessing the images
import numpy as np    # for mathematical operations
from keras.utils import np_utils
from skimage.transform import resize   # for resizing images
from sklearn.model_selection import train_test_split
from glob import glob
from tqdm import tqdm

Rename the images of the dataset according to a project specific naming convention

In [ ]:
i = 0
path="/content/gdrive/MyDrive/ASL_Alphabet_Dataset/asl_alphabet_train/Z/"
for filename in os.listdir(path):
  my_dest ="Z_" + str(i) + ".jpg"
  my_source =path + filename
  my_dest =path + my_dest
  os.rename(my_source, my_dest)
  i += 1

Creating text files with the images names belonging to each class and collating it into a single text file

In [ ]:
f= open("Z.txt","w+")
images = glob("/content/gdrive/MyDrive/ASL_Alphabet_Dataset/asl_alphabet_train/Z/*.jpg")
train_image = []
train_class = []
for i in tqdm(range(len(images))):
    # creating the image name
    train_image.append(images[i].split('/')[7])
    f.write('Z/'+train_image[i]+"\n")

100%|██████████| 7410/7410 [00:00<00:00, 270052.42it/s]


Reading the image name from imageListNew.txt file and assign them to train array list.

In [ ]:
# open the .txt file which have names of training images
f = open("/content/gdrive/MyDrive/imageListNew.txt", "r")
temp = f.read()
images = temp.split('\n')

# creating a dataframe having images names
train = pd.DataFrame()
train['image_name'] = images
train = train[:-1]
train.head()

image_name
0  A/A_0.jpg
1  A/A_1.jpg
2  A/A_2.jpg
3  A/A_3.jpg
4  A/A_4.jpg

Reading the image name from imageListNew.txt file and assign them to test array list.

In [ ]:
# open the .txt file which have names of test images
f = open("/content/gdrive/MyDrive/imageListNew.txt", "r")
temp = f.read()
images = temp.split('\n')

# creating a dataframe having images names
test = pd.DataFrame()
test['image_name'] = images
test = test[:-1]
test.head()

image_name
0  A/A_0.jpg
1  A/A_1.jpg
2  A/A_2.jpg
3  A/A_3.jpg
4  A/A_4.jpg

Creating tag for training and testing images

In [ ]:
# creating tags for training image
train_image_tag = []
for i in range(train.shape[0]):
    train_image_tag.append(train['image_name'][i].split('/')[0])
    
train['tag'] = train_image_tag

# creating tags for test image
test_image_tag = []
for i in range(test.shape[0]):
    test_image_tag.append(test['image_name'][i].split('/')[0])
    
test['tag'] = test_image_tag

Reading all the images and adding them to a single CSV file.

In [ ]:
# getting the names of all the images
train_image = []
train_class = []
for i in tqdm(range(len(images))):
  images_new = glob("/content/gdrive/MyDrive/ASL_Alphabet_Dataset/asl_alphabet_train/"+images[i])
  #print(images_new)
  #for i in tqdm(range(len(images_new))):
      # creating the image name
  train_image.append(images_new[0].split('/')[7])
  #print(train_image)
      # creating the class of image
  classes = (images_new[0].split('_')[4].split('/'))
  train_class.append(classes[1])
  #print(train_class)
      
  # storing the images and their class in a dataframe
train_data = pd.DataFrame()
train_data['image'] = train_image
train_data['class'] = train_class

  # converting the dataframe into csv file 
train_data.to_csv('/content/gdrive/MyDrive/train_new2.csv',header=True, index=False)

100%|██████████| 2626/2626 [00:00<00:00, 3234.05it/s]


Importing libraries.

In [ ]:
import keras
from keras.models import Sequential
from keras.applications.vgg16 import VGG16
from keras.layers import Dense, InputLayer, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D, GlobalMaxPooling2D
from keras.preprocessing import image
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split

Read CSV file and assign it to train array.

In [ ]:
train = pd.read_csv('/content/gdrive/MyDrive/train_new2.csv')
train.head()

image class
0  A_0.jpg     A
1  A_1.jpg     A
2  A_2.jpg     A
3  A_3.jpg     A
4  A_4.jpg     A

Preprocessing the images and Converting images to array list

In [ ]:
train_image = []

# for loop to read and store frames
for i in tqdm(range(len(images))):
    # loading the image and keeping the target size as (224,224,3)
    img = image.load_img("/content/gdrive/MyDrive/ASL_Alphabet_Dataset/asl_alphabet_train/"+images[i], target_size=(224,224,3))

     # Convert to HSV
     # Converting image color into HSV color space
    img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    # Blur the image for better edge detection
    # Bluring the image using Gaussian blur technique
    img_blur = cv2.GaussianBlur(img_hsv, (3,3), 0)

    # Sobel Edge Detection
    # Detecting edges of the image using Sobel edge detection
    sobelx = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5) # Sobel Edge Detection on the X axis
    sobely = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5) # Sobel Edge Detection on the Y axis
    sobelxy = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5)

    # converting it to array
    img = image.img_to_array(sobely)
    # normalizing the pixel value
    img = img/255
    # appending the image to the train_image list
    train_image.append(img)
    
# converting the list to numpy array
X = np.array(train_image)

# shape of the array
X.shape

100%|██████████| 2626/2626 [25:09<00:00,  1.74it/s]


(2626, 224, 224, 3)

Assigning class names for y varible and creating the training and tesing datasets with 80% allocation for training and 20% allocation for testing.

In [ ]:
# separating the target
y = train['class']
# creating the training and validation set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42, test_size=0.2, stratify = y)

In [ ]:
y_train = pd.get_dummies(y_train)
y_test = pd.get_dummies(y_test)
print(y_train)
print(y_test)

      A  B  C  D  E  F  G  H  I  J  ...  Q  R  S  T  U  V  W  X  Y  Z
2025  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  1  0  0  0  0  0
1082  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
1854  0  0  0  0  0  0  0  0  0  0  ...  0  0  1  0  0  0  0  0  0  0
2033  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  1  0  0  0  0  0
359   0  0  0  1  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
...  .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
1532  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
951   0  0  0  0  0  0  0  0  0  1  ...  0  0  0  0  0  0  0  0  0  0
78    1  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
1567  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
1951  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  1  0  0  0  0  0  0

[2100 rows x 26 columns]
      A  B  C  D  E  F  G  H  I  J  ...  Q  R  S  T  U  V  W  X  Y  Z
1555  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0 

Assigning VGG16 model as a base_model

In [ ]:
base_model = VGG16(weights='imagenet', include_top=False)

58900480/58889256 [==============================] - 0s 0us/step


Extracting features of training images

In [ ]:
# extracting features for training images
X_train = base_model.predict(X_train)
X_train.shape

(2100, 7, 7, 512)

Extracting features of testing images

In [ ]:
# extracting features for validation images
X_test = base_model.predict(X_test)
X_test.shape

(526, 7, 7, 512)

Reshaping the training as well as validation frames into a single dimension

In [ ]:
# reshaping the training as well as validation frames in single dimension
X_train = X_train.reshape(2100, 7*7*512)
X_test = X_test.reshape(526, 7*7*512)

Normalizing the pixel values

In [ ]:
# normalizing the pixel values
max = X_train.max()
X_train = X_train/max
X_test = X_test/max

Checking the shape of images

In [ ]:
# shape of images
X_train.shape

(2100, 25088)

Defining the model architecture

In [ ]:
#defining the model architecture
model = Sequential()
model.add(Dense(1024, activation='relu', input_shape=(25088,)))
model.add(Dropout(0.5))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(26, activation='softmax'))

Defining a function to save the weights of best model. It will save only the best weights by monitoring the validation loss

In [ ]:
# defining a function to save the weights of best model
from keras.callbacks import ModelCheckpoint
mcp_save = ModelCheckpoint('/content/gdrive/MyDrive/weight.hdf5', save_best_only=True, monitor='val_loss', mode='min')

Compiling the model

In [ ]:
# compiling the model
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

Training the model

In [ ]:
# training the model
model.fit(X_train, y_train, epochs=500, validation_data=(X_test, y_test), callbacks=[mcp_save], batch_size=128)

Epoch 1/500
17/17 [==============================] - 10s 519ms/step - loss: 3.3311 - accuracy: 0.0410 - val_loss: 3.2097 - val_accuracy: 0.1179
Epoch 2/500
17/17 [==============================] - 8s 479ms/step - loss: 3.2406 - accuracy: 0.0619 - val_loss: 3.1364 - val_accuracy: 0.1635
Epoch 3/500
17/17 [==============================] - 8s 485ms/step - loss: 3.0980 - accuracy: 0.1086 - val_loss: 2.8240 - val_accuracy: 0.2738
Epoch 4/500
17/17 [==============================] - 8s 470ms/step - loss: 2.8367 - accuracy: 0.1510 - val_loss: 2.4127 - val_accuracy: 0.3422
Epoch 5/500
17/17 [==============================] - 8s 462ms/step - loss: 2.5216 - accuracy: 0.2410 - val_loss: 1.9732 - val_accuracy: 0.5133
Epoch 6/500
17/17 [==============================] - 8s 470ms/step - loss: 2.1619 - accuracy: 0.3219 - val_loss: 1.4600 - val_accuracy: 0.6065
Epoch 7/500
17/17 [==============================] - 8s 499ms/step - loss: 1.8102 - accuracy: 0.4010 - val_loss: 1.1292 - val_accuracy: 0.686

In [ ]:
pred = model.predict(X_test)

In [ ]:
print(pred)
print(len(pred))

[[0.03786273 0.04032242 0.03696421 ... 0.0386578  0.03895468 0.03586298]
 [0.03808571 0.04053544 0.03676488 ... 0.03774924 0.03878539 0.03599171]
 [0.03876172 0.04034213 0.03742439 ... 0.03824721 0.03822476 0.03600995]
 ...
 [0.03827977 0.04057586 0.03709904 ... 0.03790844 0.03811371 0.03586285]
 [0.03858394 0.03999026 0.03718933 ... 0.03801576 0.03824792 0.03561423]
 [0.03806969 0.04052994 0.03668017 ... 0.03789432 0.03889007 0.03616674]]
526


In [ ]:
from sklearn import metrics
print(metrics.confusion_matrix(y_test, pred[i]))

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(y_test, pred))

In [ ]:
from sklearn.metrics._plot.roc_curve import plot_roc_curve
plot_roc_curve(model, X_test, pred)

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.preprocessing import image
import numpy as np
import pandas as pd
from tqdm import tqdm
from keras.applications.vgg16 import VGG16
import cv2
import math
import os
from glob import glob
from scipy import stats as s

In [ ]:
base_model = VGG16(weights='imagenet', include_top=False)

In [ ]:
#defining the model architecture
model = Sequential()
model.add(Dense(1024, activation='relu', input_shape=(25088,)))
model.add(Dropout(0.5))
model.add(Dense(512, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(26, activation='softmax'))

In [ ]:
# loading the trained weights
model.load_weights("/content/gdrive/MyDrive/weight.hdf5")

In [ ]:
# compiling the model
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [ ]:
# getting the test list
f = open("/content/gdrive/MyDrive/imageListNew.txt", "r")
temp = f.read()
images = temp.split('\n')

# creating the dataframe
test = pd.DataFrame()
test['image_name'] = images
test = test[:-1]
test_images = test['image_name']
test.head()

image_name
0  A/A_0.jpg
1  A/A_1.jpg
2  A/A_2.jpg
3  A/A_3.jpg
4  A/A_4.jpg

In [ ]:
# creating the tags
train = pd.read_csv('/content/gdrive/MyDrive/train_new2.csv')
y = train['class']
y = pd.get_dummies(y)

In [ ]:
# creating two lists to store predicted and actual tags
from sklearn.metrics import accuracy_score

# for loop to read and store frames
#for i in tqdm(range(len(images))):

prediction_images = []
# loading the image and keeping the target size as (224,224,3)
#image = glob("/content/gdrive/MyDrive/ASL_Alphabet_Dataset/asl_alphabet_train/"+images[i], target_size=(224,224,3))

img = image.load_img("/content/gdrive/MyDrive/ASL_Alphabet_Dataset/asl_alphabet_train/D/D_20.jpg", target_size=(224,224,3))

  # Convert to HSV
img_hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
# Blur the image for better edge detection
img_blur = cv2.GaussianBlur(img_hsv, (3,3), 0)

# Sobel Edge Detection
sobelx = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=0, ksize=5) # Sobel Edge Detection on the X axis
sobely = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=0, dy=1, ksize=5) # Sobel Edge Detection on the Y axis
sobelxy = cv2.Sobel(src=img_blur, ddepth=cv2.CV_64F, dx=1, dy=1, ksize=5)

# converting it to array
img = image.img_to_array(sobely)

# normalizing the pixel value
img = img/255
# appending the image to the train_image list
prediction_images.append(img)
    
# converting all the frames for a test video into numpy array
prediction_images = np.array(prediction_images)
# extracting features using pre-trained model
prediction_images = base_model.predict(prediction_images)
# converting features in one dimensional array
prediction_images = prediction_images.reshape(prediction_images.shape[0], 7*7*512)
# predicting tags for each array
prediction = np.argmax(model.predict(prediction_images), axis=1)
print(prediction)
print(y.columns[prediction])

[3]
Index(['D'], dtype='object')
